### PR TITLE
FW release 2.8.5, refresh existing translations

### PR DESCRIPTION
**Pull request by mmilata**
* firmware for T3T1 only
* T2B1, T2T1, T3B1: update latest translations from current git, make sure they include `it-IT`, `pt-BR`, `tr-TR`

### CODE REVIEW

**Review by komret — APPROVED** [review]

**Comment by vdovhanych** [comment]
@mmilata Should we close this? I think we decided not to do the release this month right?

**Comment by mmilata** [comment]
The 2.8.5 firmware should be definitely dropped, not sure about the translations for existing models.

**Comment by mmilata** [comment]
Note to self: if we decide to release the translations, don't forget to add 2.8.3 blobs for T3T1.

**Comment by mmilata** [comment]
Ok, please close it, I'll open a new one with the translations. @vdovhanych

**Pull request closed without merging**
