### PR TITLE
Public blog post for November release

### LINKED ISSUE #6984: Firmware udpate change log linked to draft blogpost
**Describe the bug**
Looks like link to firmware update is linked to blogpost draft.
Medium asks you to login to proceed /no way to skip it.

Then you are navigated from
https://blog.trezor.io/trezor-suite-update-and-trezor-model-t-firmware-november-2022-3aff90dc30a3
to
https://medium.com/@satoshilabs/3aff90dc30a3

`An update for Trezor Suite (version 22.11.X) `

**Steps to reproduce:**
1. Connect empty Trezor model T
2. When asked to install firmware hover over version and 
3. Click on `View all` in displayed modal.
4. Observe browser behavior

**Info:**
 - Suite version: web 22.11.1 (73ccf723353e0575a64f58b2f5775d20f072311f)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:107.0) Gecko/20100101 Firefox/107.0
 - OS: MacIntel
 - Screen: 1584x990
 - Device: model T   (revision null)
 - Transport: bridge 2.0.32

**Screenshots:**
image

image

image

### PR DESCRIPTION
**Pull request by sime**
Fixes https://github.com/trezor/trezor-suite/issues/6984

### CODE REVIEW

**Comment by vdovhanych** [comment]
This won't fix the suite bug, but we should fix it here, also.

**Comment by vdovhanych** [comment]
For suite its needed to be fixed [here](https://github.com/trezor/trezor-suite/commit/ea10340fa12eb8641e405d51ff4c957bd268a3e0#diff-fb575f3bf94ffa43e0b52102ea911ca91232066ad6cbf7569ac3a3bccca63ebaR12) and app to be rebuilt and deploy a new version

**Comment by sime** [comment]
@vdovhanych New PR opened: https://github.com/trezor/trezor-suite/pull/7020

**Comment by vdovhanych** [comment]
fixed on the blog.

**Pull request closed without merging**
