### PR TITLE
Updated terms for coinjoin purpose

### PR DESCRIPTION
**Pull request by hynek-jina**
Files `coinjoin-terms.pdf` and `wallet-terms.pdf` are identical from this change.
We could remove one of them → and update it in Suite as well

### CODE REVIEW

**Comment by tsusanka** [comment]
So can we remove coinjoin-terms.pdf or that would require changes in Suite?

**Comment by hynek-jina** [comment]
That would require change in Suite.. I will prepare the change..

**Comment by hynek-jina** [comment]
Done in: https://github.com/trezor/trezor-suite/pull/7726

**Comment by tsusanka** [comment]
Ok, we should keep it here for a while because it is in the older versions I guess right?

**Pull request merged**
