### PR TITLE
Add signed translations files for firmware

### PR DESCRIPTION
**Pull request by peter-sanderson**
Adding files for firmware translations.

### CODE REVIEW

**Review by komret — APPROVED** [review]

**Review by vdovhanych — APPROVED** [review]

**Review by vdovhanych — APPROVED** [review]

**Comment by vdovhanych** [comment]
Shouldnt we also udpate the releases json to include the translations in there?

**Comment by peter-sanderson** [comment]
@vdovhanych Those were updated for Suite here: https://github.com/trezor/trezor-suite/pull/11503

**Comment by vdovhanych** [comment]
It should be updated here as well for connect. Connect should be looking at the `releases.json` here if I'm not mistaken.

**Comment by komret** [comment]
@vdovhanych  If we update `releases.json`, we should upload the firmware binaries along with it, no? Otherwise, Suite will offer update, but it will fail. Can we add them to this PR?

**Comment by komret** [comment]
But we don't want to offer the new firmware in production yet :/

**Comment by komret** [comment]
If we cannot upload the firmware binaries or update `releases.json` before the release, let's just upload the translation binaries. Desktop app has `releases.json` bundled so we can test it there.

**Pull request merged**
