### PR TITLE
chore: add t2b1 firmware

### PR DESCRIPTION
**Pull request by vdovhanych**

### CODE REVIEW

**Comment by prusnak** [comment]
I prefer we add 2.6.3 as the first firmware because these have the correct vendor headers (signed today) and we skip 2.6.2 for t2b1 in the data repo completely. 

cc @matejcik

**Comment by kewde** [comment]
Any ETA on v2.6.3 landing here?

**Comment by Hannsek** [comment]
@kewde Probably today.

**Comment by vdovhanych** [comment]
@matejcik can you take a quick look, please? Also, I forgot what the decision was do we still put new firmware for TT into the `/2/` folder?

**Comment by matejcik** [comment]
i don't think we need to put the firmware _binaries_ in `/2/` because `releases.json` spells out the download path

we do, however, need to maintain identical `releases.json` in `/2/` and `/t2t1/`

**Review by matejcik — CHANGES_REQUESTED** [review]
data LGTM (didn't check the binaries, only releases.json fingerprints)
please copy over the changes from `/2/releases.json` to `/t2t1/releases.json`

**Comment by vdovhanych** [comment]
Right, I missed the t2t1 `releases.json` should be fixed now. Let's keep it duplicate for now and ill update it on the next firmware update to only have firmware files in `t2t1` folder.

**Review by matejcik — APPROVED** [review]

**Pull request merged**
