### PR TITLE
feat(fw): add device authentication public key whitelist

### PR DESCRIPTION
**Pull request by matejcik**
This should be the source of truth for https://github.com/trezor/trezor-suite/blob/develop/packages/connect/src/data/deviceAuthenticityConfig.ts#L48

What is missing here is any kind of signature over these files -- kind of crucial if you ask me, but there is no straightforward way to add it. We were discussing using the equivalent of Suite messaging system for it?

cc @tsusanka @komret @mroz22

### CODE REVIEW

**Comment by mroz22** [comment]
ack for the source of truth part

**Comment by komret** [comment]
There is a requirement for onboarding to work offline, so we need to have the source of truth in Suite...

**Comment by matejcik** [comment]
> There is a requirement for onboarding to work offline, so we need to have the source of truth in Suite...

no, you need a _copy_ of the source of truth in Suite :)

**Comment by matejcik** [comment]
specifically, what I'm proposing here is that these are the master files that are published on data.tio, and Suite grabs them from here in the same process as grabbing FW images

**Comment by mroz22** [comment]
yes, we should have some good automation for all those sources of truth. There are many things we should improve and we can start here. @karliatto could you check on it? a script that would check trezor-common submodule and update the respective file in connect when needed? It could be a nightl job opening PR maybe?

**Comment by karliatto** [comment]
> yes, we should have some good automation for all those sources of truth. There are many things we should improve and we can start here. @karliatto could you check on it? a script that would check trezor-common submodule and update the respective file in connect when needed? It could be a nightl job opening PR maybe?

Sure, having a look at that.

**Review by tsusanka — APPROVED** [review]
Confirming that this equals the pub keys we have in Suite.

We can merge now, and we will discuss how to improve this by signing.

**Comment by tsusanka** [comment]
@mroz22 @karliatto made an issue in Suite repo: https://github.com/trezor/trezor-suite/issues/12982

**Pull request merged**
