### PR TITLE
add dev and readme to files structure

### PR DESCRIPTION
**Pull request by vdovhanych**
Add dev folder with readme to explain what it is. It is intended for deploying for example built emulators, blockbook binaries used across our process with the intention to have it accessible from outside and having trusted storage for all these files. I suggest having the structure as dev/suite dev/firmware and so on.

### CODE REVIEW

**Comment by tsusanka** [comment]
I have some nit-picks, may I force-push for simplicity?

**Comment by vdovhanych** [comment]
> I have some nit-picks, may I force-push for simplicity?

Yes, sure!

**Comment by tsusanka** [comment]
Please review.

**Comment by vdovhanych** [comment]
> Please review.

Looks good

**Pull request merged**
